export const BASE_URL = 'https://raw.githubusercontent.com/misspia/assets/master/audio/';


const Audio = {
  elemId: 'audio',
  // tester: require('./audio/sad.mp3'),
  // tester: require('./audio/Amy Winehouse - Back to Black ( EFIX & EDGAR ft XKAEM cover ).mp3'),
  // tester: require('./audio/afraid-to-be-cool.mp3'),
  // tester: require('./audio/need-for-speed.mp3'),
  // tester: require('./audio/infinity.mp3'),
  // tester: require('./audio/devil.mp3'),
  // tester: require('./audio/disowned.mp3'),
  // tester: require('./audio/chaos.mp3'),
  // tester: require('./audio/Talking To The Moon (Bruno Mars Remix).mp3'),
  // tester: require('./audio/Lana Del Rey - Gods & Monsters.mp3'),
  // tester: require('./audio/Rosenfeld - like u.mp3'),
  // tester: require('./audio/chemicalx.mp3'),
  // tester: require('./audio/Hades - Good Riddance (Orpheus Only).mp3'),
  // tester: require('./audio/Good Riddance (feat Ashley Barrett).mp3'),
  // tester: require('./audio/Burn It All Down.mp3'),
  // tester: require('./audio/Midnight To Monaco - One In A Million.mp3'),
  // tester: require('./audio/Savoy and Bright Lights - The Wolf.mp3'),
  // tester: require('./audio/Midnight To Monaco - One Way Ticket.mp3'),
  // tester: require('./audio/SAINt JHN (Imanbek Remix) Vs R3hab & A Touch Of Class, All Around The Roses.mp3'),
  // tester: require('./audio/Deep Night.mp3'),
  // tester: require('./audio/Jonny Koch & Annie Sollange - Love Me [NCS Release].mp3'),
  // tester: require('./audio/The Wolf.mp3'),
  // tester: require('./audio/GD X TAEYANG (BIG BANG) – GOOD BOY.mp3'),
  // tester: require('./audio/Princess.mp3'),
  // tester: require('./audio/Way down We Go.mp3'),
  // tester: require('./audio/Hot Baby (ft. Joey Busse).mp3'),
  // tester: require('./audio/Besomage - Toxic (feat. Lunis).mp3'),
  // tester: require('./audio/Gioli & Assia - These Boots Are Made For Walkin.mp3'),
  // tester: require('./audio/The Chainsmokers - Side Effects (feat. Emily Warren) [Mielo Remix].mp3'),
  // tester: require('./audio/Thoreau X Tina Decara - Illusion [Trap Nation Premiere].mp3'),
  // tester: require('./audio/Nurko - Let Me Go (feat. Alina Renae).mp3'),
  // tester: require('./audio/Rival x Cadmium - Seasons (ft. Harley Bird) [Futuristik & Whogaux Remix] [NCS Release].mp3'),
  // tester: require('./audio/Antomage & Sarah de Warren - Astronomy ( Magic & Nightblue Co-release).mp3'),
  // tester: require('./audio/Mako - Murder [Ultra Music].mp3'),
  // tester: require('./audio/FFVII Crisis Core Soundtrack - Why.mp3'),
  // tester: require('./audio/Hologram - Full Metal Alchemist  Brotherhood (Opening 2) [Lyrics and sub-english].mp3'),
  // tester: require('./audio/Believe in Myself.mp3'),
  // tester: require('./audio/DragonBall Xenoverse - Main menu theme music [HQ_HD].mp3'),
  // tester: require('./audio/NIGHT RUNNING.mp3'),
  // tester: require('./audio/Jujutsu Kaisen Ending Full 【LOST IN PARADISE】.mp3'),
  // tester: require('./audio/Dr. STONE - Ending Full『LIFE』by Rude-α.mp3'),
  // tester: require('./audio/「Homura (炎 ) - LiSA」KAN_ENG_ROMAJI LYRICS  (Demon Slayer the movie - Mugen Train theme).mp3'),
  // tester: require('./audio/YuGiOh.mp3'),
  // tester: require('./audio/Red Swan.mp3'),
  // tester: require('./audio/The Oral Cigarettes - Hey Kids.mp3'),
  tester: require('./audio/Wild Side _ ALI.mp3'),
  // tester: require('./audio/.mp3'),
  
  
  S008: `${BASE_URL}nurko-right-now.mp3`,
  S014: `${BASE_URL}kda-popstars.mp3`,
  S015: `${BASE_URL}blue-d-nobody.mp3`,
  S016: `${BASE_URL}max-wrong.mp3`,

}

export default Audio;
